project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

knitr:
  opts_chunk:
    out.width: "100%"
    out.height: "100%"

book:
  title: "HFMD 2023"
  chapters:
    - index.qmd
    - sero.qmd
    # - model.qmd
    - sero_description.qmd
    - fig_manu2.qmd
    - analysis_N.qmd
    - tsir_r0.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    fig-format: svg
  pdf:
    documentclass: scrreprt

editor: visual

